services:
  - type: web
    name: arabic-auto-sync-addon
    env: docker
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 7000
    disk:
      name: cache-disk
      mountPath: /app/cache
      sizeGB: 1
